#page title
page_title                                : The Commission App for iOS                                  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1571645478                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/Icon-60@3x.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Commission                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : $3.99 CAD                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Easily track your commission earned from all of your sales.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nineone Software Inc.                                
your_link                                 :                      
your_city                                 : Vancouver                                
email_address                             : nineonesoftware@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Add Your Businesses
    description                           : Set where you conduct business and the commission split you receive for making a sale! Add an unlimited amount of businesses.
    fontawesome_icon_name                 : magic
    
  - title                                 : Add Your Products
    description                           : Set the price and cost of the products you sell. Add an unlimited amount of products.
    fontawesome_icon_name                 : star

  - title                                 : Transactions
    description                           : Transactions are what calculate your commission per sale. Transactions can hold multiple products (line items). Gave a one-off discount? Modify a product's default cost or price directly for a single transaction.
    fontawesome_icon_name                 : play-circle

  - title                                 : Commissions
    description                           : All of your commissions from all of your sales and businesses will update automatically as you create and update your transactions for the day.
    fontawesome_icon_name                 : sync

  - title                                 : At a Glance
    description                           : Easily view all of your transactions and commissions by business, product or time period. See your current expected commission for the month as well as your top selling products on the dashboard.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Reminders
    description                           : Select the days you want and you will receive a reminder on those days to remind you to enter your transactions.
    fontawesome_icon_name                 : star

  - title                                 : Data Export
    description                           : Export your transactions for a time period as a CSV (comma separated value) file. CSV files can then be imported into programs such as Excel or Numbers for further processes or sharing with accounts, co-workers etc.
    fontawesome_icon_name                 : arrow-alt-circle-down


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/pexels-pixabay-209224.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#ffffff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6C63FF"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown